# Generated by Django 3.2.2 on 2021-09-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendasoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordensoporte', models.CharField(max_length=14, unique=True, verbose_name='Orden Soporte')),
                ('fecha_soporte', models.DateField(verbose_name='Fecha Soporte')),
                ('Tiposoporte', models.CharField(max_length=50, verbose_name='Tipo Soporte')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'soporte',
                'verbose_name_plural': 'soportes',
                'db_table': 'soporte',
            },
        ),
    ]
