# Generated by Django 3.2.2 on 2021-09-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='direccion')),
                ('nit', models.CharField(max_length=10, unique=True, verbose_name='nit')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='solo incluir numeros', verbose_name='numero de Telefono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TelCliente', to='persona.tipotelefono', verbose_name='Tipo Telefono')),
            ],
            options={
                'verbose_name': 'Telefono de cliente',
                'verbose_name_plural': 'Telefonos de cliente',
            },
        ),
    ]
