# Generated by Django 3.2.2 on 2021-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto de Inicio')),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto final')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('ventasdeldia', models.CharField(default=0.0, max_length=30, verbose_name='ventas del dia')),
            ],
            options={
                'verbose_name': 'monto',
                'verbose_name_plural': 'montos',
                'db_table': 'monto',
            },
        ),
    ]
